package com.fortune.cars.business.conduct.model;
import com.fortune.common.business.base.model.BaseModel;

import java.util.Date;

/**
 * ConductValue generated by hbm2java
 */
public class ConductValue extends BaseModel implements java.io.Serializable {

	private Integer id;
	private int itemId;
	private String unit;
	private String correctValue;
	private String errorRange;
	private String currentValue;
	private Date createTime;
	private String pictureUrl;
	private String creator;
	private Integer status;

	public ConductValue() {
	}

	public ConductValue(int itemId) {
		this.itemId = itemId;
	}
	public ConductValue(int itemId, String unit, String correctValue,
			String errorRange, String currentValue, Date createTime,
			String pictureUrl, String creator, Integer status) {
		this.itemId = itemId;
		this.unit = unit;
		this.correctValue = correctValue;
		this.errorRange = errorRange;
		this.currentValue = currentValue;
		this.createTime = createTime;
		this.pictureUrl = pictureUrl;
		this.creator = creator;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getCorrectValue() {
		return this.correctValue;
	}

	public void setCorrectValue(String correctValue) {
		this.correctValue = correctValue;
	}
	public String getErrorRange() {
		return this.errorRange;
	}

	public void setErrorRange(String errorRange) {
		this.errorRange = errorRange;
	}
	public String getCurrentValue() {
		return this.currentValue;
	}

	public void setCurrentValue(String currentValue) {
		this.currentValue = currentValue;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
