package com.fortune.cars.business.conduct.model;
import com.fortune.common.business.base.model.BaseModel;

import java.util.Date;

/**
 * ConductItem generated by hbm2java
 */
public class ConductItem extends BaseModel implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer parentId;
	private String unit;
	private String code;
	private Date createTime;
	private String standValue;
	private String errorRange;
	private String standValueDesp;
	private String errorRangeDesp;
	private String currentValueDesp;
	private Integer type;
	private Integer status;

	public ConductItem() {
	}

	public ConductItem(String name, Integer parentId, String unit, String code,
			Date createTime, String standValue, String errorRange,
			String standValueDesp, String errorRangeDesp,
			String currentValueDesp, Integer type, Integer status) {
		this.name = name;
		this.parentId = parentId;
		this.unit = unit;
		this.code = code;
		this.createTime = createTime;
		this.standValue = standValue;
		this.errorRange = errorRange;
		this.standValueDesp = standValueDesp;
		this.errorRangeDesp = errorRangeDesp;
		this.currentValueDesp = currentValueDesp;
		this.type = type;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public String getStandValue() {
		return this.standValue;
	}

	public void setStandValue(String standValue) {
		this.standValue = standValue;
	}
	public String getErrorRange() {
		return this.errorRange;
	}

	public void setErrorRange(String errorRange) {
		this.errorRange = errorRange;
	}
	public String getStandValueDesp() {
		return this.standValueDesp;
	}

	public void setStandValueDesp(String standValueDesp) {
		this.standValueDesp = standValueDesp;
	}
	public String getErrorRangeDesp() {
		return this.errorRangeDesp;
	}

	public void setErrorRangeDesp(String errorRangeDesp) {
		this.errorRangeDesp = errorRangeDesp;
	}
	public String getCurrentValueDesp() {
		return this.currentValueDesp;
	}

	public void setCurrentValueDesp(String currentValueDesp) {
		this.currentValueDesp = currentValueDesp;
	}
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
