package com.fortune.rms.business.content.model;

/**
 * ContentRecommend generated by hbm2java
 */
public class ContentRecommend implements java.io.Serializable {

	private long id;
	private Long recommendId;
	private Long contentId;
	private Long displayOrder;
	private Long channelId;
    private Long cspId;

	public ContentRecommend() {
	}

	public ContentRecommend(long id) {
		this.id = id;
	}
	public ContentRecommend(long id, Long recommendId, Long contentId,
			Long displayOrder, Long channelId) {
		this.id = id;
		this.recommendId = recommendId;
		this.contentId = contentId;
		this.displayOrder = displayOrder;
		this.channelId = channelId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getRecommendId() {
		return this.recommendId;
	}

	public void setRecommendId(Long recommendId) {
		this.recommendId = recommendId;
	}
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}
	public Long getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Long displayOrder) {
		this.displayOrder = displayOrder;
	}
	public Long getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}

    public Long getCspId() {
        return cspId;
    }

    public void setCspId(Long cspId) {
        this.cspId = cspId;
    }

    /**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
