package com.fortune.rms.business.content.model;

import java.util.Date;

/**
 * ContentAudit generated by hbm2java
 */
public class ContentAudit implements java.io.Serializable {

	private long id;
	private Long contentId;
	private Long type;
	private Long status;
	private Long result;
	private String resultMsg;
	private String desp;
	private Date applyTime;
	private Long auditAdminId;
	private Date auditTime;

	public ContentAudit() {
	}

	public ContentAudit(long id) {
		this.id = id;
	}
	public ContentAudit(long id, Long contentId, Long type, Long status,
			Long result, String resultMsg, String desp, Date applyTime,
			Long auditAdminId, Date auditTime) {
		this.id = id;
		this.contentId = contentId;
		this.type = type;
		this.status = status;
		this.result = result;
		this.resultMsg = resultMsg;
		this.desp = desp;
		this.applyTime = applyTime;
		this.auditAdminId = auditAdminId;
		this.auditTime = auditTime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}
	public Long getResult() {
		return this.result;
	}

	public void setResult(Long result) {
		this.result = result;
	}
	public String getResultMsg() {
		return this.resultMsg;
	}

	public void setResultMsg(String resultMsg) {
		this.resultMsg = resultMsg;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}
	public Long getAuditAdminId() {
		return this.auditAdminId;
	}

	public void setAuditAdminId(Long auditAdminId) {
		this.auditAdminId = auditAdminId;
	}
	public Date getAuditTime() {
		return this.auditTime;
	}

	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
