package com.fortune.rms.business.content.model;

import java.util.Date;

/**
 * ContentCsp generated by hbm2java
 */
public class ContentCsp implements java.io.Serializable {

	private long id;
	private Long contentId;
	private Long cspId;
	private Long status;
	private Date statusTime;
	private Long contentAuditId;

	public ContentCsp() {
	}

	public ContentCsp(long id) {
		this.id = id;
	}
	public ContentCsp(long id, Long contentId, Long cspId, Long status,
			Date statusTime, Long contentAutidtId) {
		this.id = id;
		this.contentId = contentId;
		this.cspId = cspId;
		this.status = status;
		this.statusTime = statusTime;
		this.contentAuditId = contentAutidtId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}
	public Date getStatusTime() {
		return this.statusTime;
	}

	public void setStatusTime(Date statusTime) {
		this.statusTime = statusTime;
	}
	public Long getContentAuditId() {
		return this.contentAuditId;
	}

	public void setContentAuditId(Long contentAutidtId) {
		this.contentAuditId = contentAutidtId;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
