package com.fortune.rms.business.content.model;

import java.util.Date;

/**
 * IpRange generated by hbm2java
 */
public class ContentNotice implements java.io.Serializable {

    private long id;
    private String content;
    private Long status;
    private Date createTime;
    private Date onlineTime;
    private Date offlineTime;
    private Long cspId;
    private Long adminId;

    public ContentNotice() {
    }

    public ContentNotice(long id) {
        this.id = id;
    }

    public ContentNotice(long id, String content, Long status, Date createTime, Date onlineTime, Date offlineTime, Long cspId, Long adminId){
        this.id = id;
        this.content = content;
        this.status = status;
        this.createTime = createTime;
        this.onlineTime = onlineTime;
        this.offlineTime = offlineTime;
        this.cspId = cspId;
        this.adminId = adminId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getStatus() {
        return status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getOnlineTime() {
        return onlineTime;
    }

    public void setOnlineTime(Date onlineTime) {
        this.onlineTime = onlineTime;
    }

    public Date getOfflineTime() {
        return offlineTime;
    }

    public void setOfflineTime(Date offlineTime) {
        this.offlineTime = offlineTime;
    }

    public Long getCspId() {
        return cspId;
    }

    public void setCspId(Long cspId) {
        this.cspId = cspId;
    }

    public Long getAdminId() {
        return adminId;
    }

    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * toString return json format string of this bean
     * @return String
     */
    public String toString() {
        return com.fortune.util.JsonUtils.getJsonString(this);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getSimpleJson() {
        return com.fortune.util.JsonUtils.getJsonString(this, null);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getObjJson() {
        return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
    }

}
