package com.fortune.rms.business.content.model;

/**
 * ContentChannel generated by hbm2java
 */
public class ContentChannel implements java.io.Serializable {

	private long id;
	private Long contentId;
	private Long channelId;

	public ContentChannel() {
	}

	public ContentChannel(long id) {
		this.id = id;
	}
	public ContentChannel(long id, Long contentId, Long channelId) {
		this.id = id;
		this.contentId = contentId;
		this.channelId = channelId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}
	public Long getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
