package com.fortune.rms.business.content.model;

import com.fortune.common.business.base.model.BaseModel;
import com.fortune.rms.business.module.model.Property;

/**
 * ContentProperty generated by hbm2java
 */
public class ContentProperty extends BaseModel {

	private long id;
	private Long contentId;
	private Long propertyId;
    private Byte propertyType;  //Property的属性，只为了界面渲染速度，不保存在数据库，只是为了显示用
    private Long rowSpan;
    private Long colSpan;
    private String propertyName;//不保存在数据库，只是为了显示用
    private Long intValue;
	private String stringValue;
	private String desp;
	private String extraData;
    private String subContentId;
    private String name;
    private String thumbPic;
    private Long extraInt;
    private Long length;
    private Property property;

	public ContentProperty() {
	}

	public ContentProperty(long id) {
		this.id = id;
	}
	public ContentProperty(long id, Long contentId, Long propertyId,
			Long intValue, String stringValue, String desp, String extraData) {
		this.id = id;
		this.contentId = contentId;
		this.propertyId = propertyId;
		this.intValue = intValue;
		this.stringValue = stringValue;
		this.desp = desp;
		this.extraData = extraData;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}
	public Long getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(Long propertyId) {
		this.propertyId = propertyId;
	}
	public Long getIntValue() {
		return this.intValue;
	}

	public void setIntValue(Long intValue) {
		this.intValue = intValue;
	}
	public String getStringValue() {
		return this.stringValue;
	}

	public void setStringValue(String stringValue) {
		this.stringValue = stringValue;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public String getExtraData() {
		return this.extraData;
	}

	public void setExtraData(String extraData) {
		this.extraData = extraData;
	}

    public String getSubContentId() {
        return subContentId;
    }

    public void setSubContentId(String subContentId) {
        this.subContentId = subContentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getThumbPic() {
        return thumbPic;
    }

    public void setThumbPic(String thumbPic) {
        this.thumbPic = thumbPic;
    }

    public Long getExtraInt() {
        return extraInt;
    }

    public void setExtraInt(Long extraInt) {
        this.extraInt = extraInt;
    }

    public Long getLength() {
        return length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    public Byte getPropertyType() {
        return propertyType;
    }

    public void setPropertyType(Byte propertyType) {
        this.propertyType = propertyType;
    }

    public Long getRowSpan() {
        return rowSpan;
    }

    public void setRowSpan(Long rowSpan) {
        this.rowSpan = rowSpan;
    }

    public Long getColSpan() {
        return colSpan;
    }

    public void setColSpan(Long colSpan) {
        this.colSpan = colSpan;
    }

    @SuppressWarnings("JpaAttributeTypeInspection")
    public Property getProperty() {
        return property;
    }

    public void setProperty(Property property) {
        this.property = property;
    }
}
