package com.fortune.rms.business.ad.model;

import java.util.Date;

/**
 * Ad generated by hbm2java
 */
public class Ad implements java.io.Serializable {

	private long id;
	private String name;
	private String desp;
	private Date startTime;
	private Date endTime;
	private Long adLength;
	private Long adPlayType;
	private Long playTime;
	private Long isForce;
    private String url;
    private Long deviceId;
	public Ad() {
	}

	public Ad(long id) {
		this.id = id;
	}
	public Ad(long id, String name, String desp, Date startTime, Date endTime,
			Long adLength, Long adPlayType, Long playTime, Long isForce,String url,Long deviceId) {
		this.id = id;
		this.name = name;
		this.desp = desp;
		this.startTime = startTime;
		this.endTime = endTime;
		this.adLength = adLength;
		this.adPlayType = adPlayType;
		this.playTime = playTime;
		this.isForce = isForce;
        this.url = url;
        this.deviceId = deviceId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
	public Long getAdLength() {
		return this.adLength;
	}

	public void setAdLength(Long adLength) {
		this.adLength = adLength;
	}
	public Long getAdPlayType() {
		return this.adPlayType;
	}

	public void setAdPlayType(Long adPlayType) {
		this.adPlayType = adPlayType;
	}
	public Long getPlayTime() {
		return this.playTime;
	}

	public void setPlayTime(Long playTime) {
		this.playTime = playTime;
	}
	public Long getIsForce() {
		return this.isForce;
	}

	public void setIsForce(Long isForce) {
		this.isForce = isForce;
	}

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
