package com.fortune.rms.business.ad.model;

import com.fortune.common.business.base.model.BaseModel;

import java.util.Date;

/**
 * AdLog generated by hbm2java
 */
@SuppressWarnings("unused")
public class AdLog extends BaseModel {

	private long id;
    private Long adId;
    private String adUrlId;
    private Long channelId;
    private Long spId;
    private Date visitTime;
    private Long contentId;
    private Long adRangeId;
    private Long trainId;

    public AdLog() {
	}

	public AdLog(long id) {
		this.id = id;
	}

    public AdLog(long id, Long adId, String adUrlId, Long channelId, Long spId, Date visitTime, Long contentId, Long adRangeId,Long trainId) {
        this.id = id;
        this.adId = adId;
        this.adUrlId = adUrlId;
        this.channelId = channelId;
        this.spId = spId;
        this.visitTime = visitTime;
        this.contentId = contentId;
        this.adRangeId = adRangeId;
        this.trainId = trainId;
    }

    public Long getAdId() {
        return adId;
    }

    public void setAdId(Long adId) {
        this.adId = adId;
    }

    public String getAdUrlId() {
        return adUrlId;
    }

    public void setAdUrlId(String adUrlId) {
        this.adUrlId = adUrlId;
    }

    public Long getChannelId() {
        return channelId;
    }

    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    public Long getSpId() {
        return spId;
    }

    public void setSpId(Long spId) {
        this.spId = spId;
    }

    public Date getVisitTime() {
        return visitTime;
    }

    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

    public Long getContentId() {
        return contentId;
    }

    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    public Long getAdRangeId() {
        return adRangeId;
    }

    public void setAdRangeId(Long adRangeId) {
        this.adRangeId = adRangeId;
    }

    public Long getTrainId() {
        return trainId;
    }

    public void setTrainId(Long trainId) {
        this.trainId = trainId;
    }
}
