package com.fortune.rms.business.ad.model;

import com.fortune.common.business.base.model.BaseModel;

/**
 * AdRange generated by hbm2java
 */
public class AdRange extends BaseModel {

	private long id;
	private Long adId;
	private Long type;
    private Long pos;
	private Long cid;
    private String adName;
    private String desertName;
    private Long lineId;
    private String lineName;
    private Ad ad;
	public AdRange() {
	}

    public AdRange(long id, Long adId, Long type, Long pos, Long cid, String adName, String desertName, Long lineId, String lineName) {
        this.id = id;
        this.adId = adId;
        this.type = type;
        this.pos = pos;
        this.cid = cid;
        this.adName = adName;
        this.desertName = desertName;
        this.lineId = lineId;
        this.lineName = lineName;
    }

    public AdRange(long id) {
		this.id = id;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getAdId() {
		return this.adId;
	}

	public void setAdId(Long adId) {
		this.adId = adId;
	}
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}
	public Long getCid() {
		return this.cid;
	}

	public void setCid(Long cid) {
		this.cid = cid;
	}

    public String getDesertName() {
        return desertName;
    }

    public void setDesertName(String channelName) {
        this.desertName = channelName;
    }

    public String getAdName() {
        return adName;
    }

    public void setAdName(String adName) {
        this.adName = adName;
    }

    public Long getPos() {
        return pos;
    }

    public void setPos(Long pos) {
        this.pos = pos;
    }

    public Long getLineId() {
        return lineId;
    }

    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    public String getLineName() {
        return lineName;
    }

    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    public Ad getAd() {
        return ad;
    }

    public void setAd(Ad ad) {
        this.ad = ad;
    }
}
