package com.fortune.rms.business.ad.model;

/**
 * AdUrl generated by hbm2java
 */
public class AdUrl implements java.io.Serializable {

	private long id;
	private String name;
	private String desp;
	private Long type;
	private String url;
	private Long playPercent;

	public AdUrl() {
	}

	public AdUrl(long id) {
		this.id = id;
	}
	public AdUrl(long id, String name, String desp, Long type, String url,
			Long playPercent) {
		this.id = id;
		this.name = name;
		this.desp = desp;
		this.type = type;
		this.url = url;
		this.playPercent = playPercent;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	public Long getPlayPercent() {
		return this.playPercent;
	}

	public void setPlayPercent(Long playPercent) {
		this.playPercent = playPercent;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
