package com.fortune.rms.business.system.model;

/**
 * AreaIpRange generated by hbm2java
 */
public class AreaIpRange implements java.io.Serializable {

	private long id;
	private Long areaId;
	private Long ipRangeId;

    private String  areaName;
    private String    ipRangeName;


	public AreaIpRange() {
	}

	public AreaIpRange(long id) {
		this.id = id;
	}
	public AreaIpRange(long id, Long areaId, Long ipRangeId) {
		this.id = id;
		this.areaId = areaId;
		this.ipRangeId = ipRangeId;
	}

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getIpRangeName() {
        return ipRangeName;
    }

    public void setIpRangeName(String ipRangeName) {
        this.ipRangeName = ipRangeName;
    }
    
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Long areaId) {
		this.areaId = areaId;
	}
	public Long getIpRangeId() {
		return this.ipRangeId;
	}

	public void setIpRangeId(Long ipRangeId) {
		this.ipRangeId = ipRangeId;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
