package com.fortune.rms.business.system.model;

import com.fortune.common.business.base.model.BaseModel;

/**
 * Device generated by hbm2java
 */
public class Device extends BaseModel {

	private long id;
	private String name;
	private Long type;
	private String ip;
	private String url;
	private Long status;
	private Long ftpPort;
	private String ftpUser;
	private String ftpPwd;
	private String ftpPath;
    private String localPath;
    private Long maxTask;
    private Integer monitorPort;
    private String exportPath;

    private boolean selected;

	public Device() {
	}

    public Device(long id, String name, Long type, String ip, String url, Long status, Long ftpPort, String ftpUser,
                  String ftpPwd, String ftpPath, String localPath, Long maxTask, Integer monitorPort, String exportPath) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.ip = ip;
        this.url = url;
        this.status = status;
        this.ftpPort = ftpPort;
        this.ftpUser = ftpUser;
        this.ftpPwd = ftpPwd;
        this.ftpPath = ftpPath;
        this.localPath = localPath;
        this.maxTask = maxTask;
        this.monitorPort = monitorPort;
        this.exportPath = exportPath;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
		return this.name;
	}


	public void setName(String name) {
		this.name = name;
	}

    public Long getMaxTask() {
        return maxTask;
    }

    public void setMaxTask(Long maxTask) {
        this.maxTask = maxTask;
    }

    public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}
	public Long getFtpPort() {
		return this.ftpPort;
	}

	public void setFtpPort(Long ftpPort) {
		this.ftpPort = ftpPort;
	}
	public String getFtpUser() {
		return this.ftpUser;
	}

	public void setFtpUser(String ftpUser) {
		this.ftpUser = ftpUser;
	}
	public String getFtpPwd() {
		return this.ftpPwd;
	}

	public void setFtpPwd(String ftpPwd) {
		this.ftpPwd = ftpPwd;
	}
	public String getFtpPath() {
		return this.ftpPath;
	}

	public void setFtpPath(String ftpPath) {
		this.ftpPath = ftpPath;
	}

    public String getExportPath() {
        return exportPath;
    }

    public void setExportPath(String exportPath) {
        this.exportPath = exportPath;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public String getLocalPath() {
        return localPath;
    }

    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    public Integer getMonitorPort() {
        return monitorPort;
    }

    public void setMonitorPort(Integer monitorPort) {
        this.monitorPort = monitorPort;
    }

    public String getSafeServerIp() {
        if(ip==null||"".equals(ip)||"serverIP".equals(ip)||"serverIp".equals(ip)){
            return "127.0.0.1";
        }
        return ip;
    }
}

