package com.fortune.rms.business.system.model;

import com.fortune.util.StringUtils;

/**
 * IpRange generated by hbm2java
 */
public class IpRange implements java.io.Serializable {

	private long id;
	private String name;
	private String desp;
	private Long ipFrom;
	private Long ipTo;
    private Long areaId;

	public IpRange() {
	}

	public IpRange(long id) {
		this.id = id;
	}
	public IpRange(long id, String name, String desp, Long ipFrom, Long ipTo, Long areaId) {
		this.id = id;
		this.name = name;
		this.desp = desp;
		this.ipFrom = ipFrom;
		this.ipTo = ipTo;
        this.areaId = areaId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public Long getIpFrom() {
		return this.ipFrom;
	}

	public void setIpFrom(Long ipFrom) {
		this.ipFrom = ipFrom;
	}
	public Long getIpTo() {
		return this.ipTo;
	}

	public void setIpTo(Long ipTo) {
		this.ipTo = ipTo;
	}

    public String getIpFromStr(){
        return StringUtils.longIp2String(ipFrom);
    }

    public void setIpFromStr(String ipFromStr){
        ipFrom = StringUtils.string2IpLong(ipFromStr);
    }

    public String getIpToStr(){
        return StringUtils.longIp2String(ipTo);
    }

    public void setIpToStr(String ipToStr){
        ipTo = StringUtils.string2IpLong(ipToStr);
    }

    public Long getAreaId() {
        return areaId;
    }

    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
