package com.fortune.rms.business.system.model;

/**
 * PhoneRange generated by hbm2java
 */
public class PhoneRange implements java.io.Serializable {

    private long id;
    private String name;
    private String desp;
    private Long phoneFrom;
    private Long phoneTo;
    private Long areaId;

    public PhoneRange() {
    }

    public PhoneRange(long id) {
        this.id = id;
    }
    public PhoneRange(long id, String name, String desp, Long phoneFrom, Long phoneTo, Long areaId) {
        this.id = id;
        this.name = name;
        this.desp = desp;
        this.phoneFrom = phoneFrom;
        this.phoneTo = phoneTo;
        this.areaId = areaId;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getDesp() {
        return this.desp;
    }

    public void setDesp(String desp) {
        this.desp = desp;
    }
    public Long getPhoneFrom() {
        return this.phoneFrom;
    }

    public void setPhoneFrom(Long phoneFrom) {
        this.phoneFrom = phoneFrom;
    }
    public Long getPhoneTo() {
        return this.phoneTo;
    }

    public void setPhoneTo(Long phoneTo) {
        this.phoneTo = phoneTo;
    }

    public Long getAreaId() {
        return areaId;
    }

    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * toString return json format string of this bean
     * @return String
     */
    public String toString() {
        return com.fortune.util.JsonUtils.getJsonString(this);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getSimpleJson() {
        return com.fortune.util.JsonUtils.getJsonString(this, null);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getObjJson() {
        return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
    }

}
