package com.fortune.common.business.security.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdminPermission generated by hbm2java
 */
//@Entity
//@Table(name = "SECURITY_OPERATOR_PERMISSION")
//@SequenceGenerator(name = "FORTUNE_GLOBAL_SEQ", sequenceName = "FORTUNE_GLOBAL_SEQ")
public class AdminPermission implements java.io.Serializable {

	private long id;
	private long adminId;
	private long permissionId;

    public AdminPermission() {
	}

	public AdminPermission(long id, long adminId, long permissionId) {
		this.id = id;
		this.adminId = adminId;
		this.permissionId = permissionId;
	}

//    @Id
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "FORTUNE_GLOBAL_SEQ")
//	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

//	@Column(name = "OPERATORID", nullable = false, precision = 16, scale = 0)
	public long getAdminId() {
		return this.adminId;
	}

	public void setAdminId(long adminId) {
		this.adminId = adminId;
	}

//	@Column(name = "PERMISSIONID", nullable = false, precision = 16, scale = 0)
    @SuppressWarnings("unused")
	public long getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(long permissionId) {
		this.permissionId = permissionId;
	}
    public String toString(){
        return com.fortune.util.JsonUtils.getJsonString(this);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getSimpleJson(){
        return com.fortune.util.JsonUtils.getJsonString(this,null);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getObjJson(){
        return com.fortune.util.JsonUtils.getJsonString(this,"obj.");
    }

}
