package com.fortune.common.business.security.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdminRole generated by hbm2java
 */
@Entity
@Table(name = "ADMIN_ROLE")
@SequenceGenerator(name = "FORTUNE_GLOBAL_SEQ", sequenceName = "FORTUNE_GLOBAL_SEQ")
public class AdminRole implements java.io.Serializable {

	private Integer id;
	private Integer adminId;
	private Integer roleId;
    private Integer cspId;

    public AdminRole() {
	}

	public AdminRole(Integer id, Integer adminId, Integer roleId,Integer cspId) {
		this.id = id;
		this.adminId = adminId;
		this.roleId = roleId;
        this.cspId = cspId;
	}

    @Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "FORTUNE_GLOBAL_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ADMIN_ID", nullable = false, precision = 16, scale = 0)
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	@Column(name = "ROLE_ID", nullable = false, precision = 16, scale = 0)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

    @Column(name = "CSP_ID", nullable = false, precision = 16, scale = 0)
    public Integer getCspId() {
        return cspId;
    }

    public void setCspId(Integer cspId) {
        this.cspId = cspId;
    }

    public String toString(){
        return com.fortune.util.JsonUtils.getJsonString(this);
    }
    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getSimpleJson(){
        return com.fortune.util.JsonUtils.getJsonString(this,null);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getObjJson(){
        return com.fortune.util.JsonUtils.getJsonString(this,"obj.");
    }

}
