package com.fortune.common.business.security.model;

import com.fortune.common.business.base.model.BaseModel;

/**
 * RolePermission generated by hbm2java
 */
public class RoleMenu extends BaseModel {
	private int id;
	private Integer roleId;
	private Integer menuId;

    public RoleMenu() {
	}

	public RoleMenu(Integer id, Integer roleId, Integer menuId) {
		this.id = id;
		this.roleId = roleId;
		this.menuId = menuId;
	}

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public Integer getMenuId() {
        return menuId;
    }

    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}
