package com.fortune.common.business.security.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name = "ROLE_PERMISSION")
@SequenceGenerator(name = "FORTUNE_GLOBAL_SEQ", sequenceName = "FORTUNE_GLOBAL_SEQ")
public class RolePermission implements java.io.Serializable {

	private Integer id;
	private Integer roleid;
	private Integer permissionid;
    private Permission permission;
    private Role role;

//    @ManyToOne(fetch = FetchType.EAGER)
//    @JoinColumn(name = "PERMISSIONID", unique = true, nullable = true, insertable = false, updatable = false)
    @SuppressWarnings("JpaAttributeTypeInspection")
    public Permission getPermission() {
        return permission;
    }

    public void setPermission(Permission permission) {
        this.permission = permission;
    }
//    @ManyToOne(fetch = FetchType.EAGER)
//    @JoinColumn(name = "ROLEID", unique = true, nullable = true, insertable = false, updatable = false)
    @SuppressWarnings("JpaAttributeTypeInspection")
    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public RolePermission() {
	}

	public RolePermission(Integer id, Integer roleid, Integer permissionid) {
		this.id = id;
		this.roleid = roleid;
		this.permissionid = permissionid;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "FORTUNE_GLOBAL_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 16, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	@Column(name = "ROLEID", nullable = false, precision = 16, scale = 0)
	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

//	@Column(name = "PERMISSIONID", nullable = false, precision = 16, scale = 0)
	public Integer getPermissionid() {
		return this.permissionid;
	}

	public void setPermissionid(Integer permissionid) {
		this.permissionid = permissionid;
	}

    public String toString(){
        return com.fortune.util.JsonUtils.getJsonString(this);
    }
    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getSimpleJson(){
        return com.fortune.util.JsonUtils.getJsonString(this,null);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getObjJson(){
        return com.fortune.util.JsonUtils.getJsonString(this,"obj.");
    }

}
