package com.fortune.rms.business.log.model;

import java.util.Date;

/**
 * VisitDayCpLog generated by hbm2java
 */
public class VisitDayCpLog implements java.io.Serializable {

	private long id;
	private Long cpId;
	private Date day;
	private Long count;
	private Long length;

	public VisitDayCpLog() {
	}

	public VisitDayCpLog(long id) {
		this.id = id;
	}
	public VisitDayCpLog(long id, Long cpId, Date day, Long count, Long length) {
		this.id = id;
		this.cpId = cpId;
		this.day = day;
		this.count = count;
		this.length = length;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getCpId() {
		return this.cpId;
	}

	public void setCpId(Long cpId) {
		this.cpId = cpId;
	}
	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}
	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}
	public Long getLength() {
		return this.length;
	}

	public void setLength(Long length) {
		this.length = length;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
