package com.fortune.rms.business.log.model;

import java.util.Date;

/**
 * VisitDaySpLog generated by hbm2java
 */
public class VisitDaySpLog implements java.io.Serializable {

	private long id;
	private Long spId;
	private Date day;
	private Long count;
	private Long length;

	public VisitDaySpLog() {
	}

	public VisitDaySpLog(long id) {
		this.id = id;
	}
	public VisitDaySpLog(long id, Long spId, Date day, Long count, Long length) {
		this.id = id;
		this.spId = spId;
		this.day = day;
		this.count = count;
		this.length = length;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getSpId() {
		return this.spId;
	}

	public void setSpId(Long spId) {
		this.spId = spId;
	}
	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}
	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}
	public Long getLength() {
		return this.length;
	}

	public void setLength(Long length) {
		this.length = length;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
