package com.fortune.rms.business.log.model;

import java.util.Date;

/**
 * VisitDayAreaLog generated by hbm2java
 */
public class VisitDayAreaLog implements java.io.Serializable {

	private long id;
	private Long spId;
	private Long cpId;
	private Long channelId;
	private Long areaId;
	private Date day;
	private Long count;
	private Long length;

	public VisitDayAreaLog() {
	}

	public VisitDayAreaLog(long id) {
		this.id = id;
	}
	public VisitDayAreaLog(long id, Long spId, Long cpId, Long channelId,
			Long areaId, Date day, Long count, Long length) {
		this.id = id;
		this.spId = spId;
		this.cpId = cpId;
		this.channelId = channelId;
		this.areaId = areaId;
		this.day = day;
		this.count = count;
		this.length = length;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getSpId() {
		return this.spId;
	}

	public void setSpId(Long spId) {
		this.spId = spId;
	}
	public Long getCpId() {
		return this.cpId;
	}

	public void setCpId(Long cpId) {
		this.cpId = cpId;
	}
	public Long getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}
	public Long getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Long areaId) {
		this.areaId = areaId;
	}
	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}
	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}
	public Long getLength() {
		return this.length;
	}

	public void setLength(Long length) {
		this.length = length;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
