package com.fortune.rms.business.log.model;

import java.util.Date;

/**
 * WebVisitLog generated by hbm2java
 */
public class WebVisitLog implements java.io.Serializable {

	private long id;
	private Long spId;
	private Long cpId;
	private Long channelId;
	private Long contentId;
	private String userIp;
	private Long areaId;
	private Date visitTime;

	public WebVisitLog() {
	}

	public WebVisitLog(long id) {
		this.id = id;
	}
	public WebVisitLog(long id, Long spId, Long cpId, Long channelId,
			Long contentId, String userIp, Long areaId, Date visitTime) {
		this.id = id;
		this.spId = spId;
		this.cpId = cpId;
		this.channelId = channelId;
		this.contentId = contentId;
		this.userIp = userIp;
		this.areaId = areaId;
		this.visitTime = visitTime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getSpId() {
		return this.spId;
	}

	public void setSpId(Long spId) {
		this.spId = spId;
	}
	public Long getCpId() {
		return this.cpId;
	}

	public void setCpId(Long cpId) {
		this.cpId = cpId;
	}
	public Long getChannelId() {
		return this.channelId;
	}

	public void setChannelId(Long channelId) {
		this.channelId = channelId;
	}
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}
	public Long getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Long areaId) {
		this.areaId = areaId;
	}
	public Date getVisitTime() {
		return this.visitTime;
	}

	public void setVisitTime(Date visitTime) {
		this.visitTime = visitTime;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
