package com.fortune.rms.business.publish.model;

import com.fortune.common.business.base.model.BaseModel;

/**
 * Channel generated by hbm2java
 */
public class Channel extends BaseModel{

	private long id;
	private String name;
	private String description;
	private Long type;
	private Long cspId;
	private String poster1;
	private String poster2;
	private Long parentId;
	private Long status;
    private boolean leaf;
    private boolean checked;
    private String parentName;
    private String code;
    private Long grade;
    private Integer auditFlag;
    private String backgroundColor;
    private String layout;
	public Channel() {
	}

	public Channel(long id) {
		this.id = id;
	}
	public Channel(long id, String name, String description, Long type,
			Long cspId, String poster1, String poster2, Long parentId,
			Long status,Long grade,Integer auditFlag,String backgroundColor,String layout) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.type = type;
		this.cspId = cspId;
		this.poster1 = poster1;
		this.poster2 = poster2;
		this.parentId = parentId;
		this.status = status;
        this.grade = grade;
        this.auditFlag = auditFlag;
        this.backgroundColor = backgroundColor;
        this.layout = layout;
	}

	// added by mlwang，比较两个Channel相等，以便contains可以正常使用
	@Override
	public boolean equals(Object object){
		boolean eq = false;

		if (object != null && object instanceof Channel){
			eq = this.id == ((Channel) object).getId();
		}

		return eq;
	}
    public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}

    public Long getGrade() {
        return grade;
    }

    public void setGrade(Long grade) {
        this.grade = grade;
    }
	public String getPoster1() {
		return this.poster1;
	}

	public void setPoster1(String poster1) {
		this.poster1 = poster1;
	}
	public String getPoster2() {
		return this.poster2;
	}

	public void setPoster2(String poster2) {
		this.poster2 = poster2;
	}
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}


    public boolean isLeaf() {
        return leaf;
    }

    public void setLeaf(boolean leaf) {
        this.leaf = leaf;
    }

    public boolean isChecked() {
        return checked;
    }

    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Integer getAuditFlag() {
        return auditFlag;
    }

    public void setAuditFlag(Integer auditFlag) {
        this.auditFlag = auditFlag;
    }

    public String getBackgroundColor() {
        return backgroundColor;
    }

    public void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
    }

    public String getLayout() {
        return layout;
    }

    public void setLayout(String layout) {
        this.layout = layout;
    }
}
