package com.fortune.rms.business.publish.model;

/**
 * Recommend generated by hbm2java
 */
public class Recommend implements java.io.Serializable {

	public static final long RECOMMEND_TYPE_SYSTEM = 1;
	public static final long RECOMMEND_TYPE_CHANNEL = 2;

	private long id;
	private String code;
	private String name;
	private String desp;
	private Long isSystem;
	private Long cspId;
	private Long type;
    private Long channelId;
    
	public Recommend() {
	}

	public Recommend(long id) {
		this.id = id;
	}
	public Recommend(long id, String code, String name, String desp,
			Long isSystem, Long cspId, Long type,Long channelId) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.desp = desp;
		this.isSystem = isSystem;
		this.cspId = cspId;
		this.type = type;
        this.channelId = channelId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public Long getIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(Long isSystem) {
		this.isSystem = isSystem;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}

    public Long getChannelId() {
        return channelId;
    }

    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
