package com.fortune.rms.business.publish.model;

/**
 * RelatedPropertyContent generated by hbm2java
 */
public class RelatedPropertyContent implements java.io.Serializable {

	private long id;
	private Long relatedPropertyId;
	private Long contentId;
	private Long cspId;
	private Long displayOrder;

	public RelatedPropertyContent() {
	}

	public RelatedPropertyContent(long id) {
		this.id = id;
	}
	public RelatedPropertyContent(long id, Long relatedPropertyId,
			Long contentId, Long cspId, Long displayOrder) {
		this.id = id;
		this.relatedPropertyId = relatedPropertyId;
		this.contentId = contentId;
		this.cspId = cspId;
		this.displayOrder = displayOrder;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getRelatedPropertyId() {
		return this.relatedPropertyId;
	}

	public void setRelatedPropertyId(Long relatedPropertyId) {
		this.relatedPropertyId = relatedPropertyId;
	}
	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Long displayOrder) {
		this.displayOrder = displayOrder;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
