package com.fortune.rms.business.publish.model;

/**
 * Related generated by hbm2java
 */
public class Related implements java.io.Serializable {

	private long id;
	private String code;
	private String name;
	private String desp;
	private Long cspId;
	private Long type;
	private Long moduleId;
	private Long propertyId;

	public Related() {
	}

	public Related(long id) {
		this.id = id;
	}
	public Related(long id, String code, String name, String desp, Long cspId,
			Long type, Long moduleId, Long propertyId) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.desp = desp;
		this.cspId = cspId;
		this.type = type;
		this.moduleId = moduleId;
		this.propertyId = propertyId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}
	public Long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Long moduleId) {
		this.moduleId = moduleId;
	}
	public Long getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(Long propertyId) {
		this.propertyId = propertyId;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
