package com.fortune.rms.business.publish.model;

import java.util.Date;

/**
 * UserHotSearch generated by hbm2java
 */

public class UserHotSearch implements java.io.Serializable{
    private long id;
    private String content;
    private Date createTime;
    private long searchCount;
    private long searchWeekCount;
    private long searchMonthCount;
    private long updateCount;
    private long searchCountStatus;
    private long type;
    private long adminId;

    public UserHotSearch(){

    }

    public UserHotSearch(long id){
        this.id = id;
    }

    public UserHotSearch(long id,String content,Date createTime,long searchCount,long searchCountStatus,long type,long adminId,
                         long searchWeekCount,long searchMonthCount,long updateCount){
        this.id = id;
        this.content = content;
        this.createTime = createTime;
        this.searchCount = searchCount;
        this.searchCountStatus = searchCountStatus;
        this.type = type;
        this.adminId = adminId;
        this.searchWeekCount = searchWeekCount;
        this.searchMonthCount = searchMonthCount;
        this.updateCount = updateCount;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public long getSearchCount() {
        return searchCount;
    }

    public void setSearchCount(long searchCount) {
        this.searchCount = searchCount;
    }

    public long getSearchCountStatus() {
        return searchCountStatus;
    }

    public void setSearchCountStatus(long searchCountStatus) {
        this.searchCountStatus = searchCountStatus;
    }

    public long getType() {
        return type;
    }

    public void setType(long type) {
        this.type = type;
    }
    public long getAdminId() {
        return adminId;
    }

    public void setAdminId(long adminId) {
        this.adminId = adminId;
    }

    public long getSearchWeekCount() {
        return searchWeekCount;
    }

    public void setSearchWeekCount(long searchWeekCount) {
        this.searchWeekCount = searchWeekCount;
    }

    public long getSearchMonthCount() {
        return searchMonthCount;
    }

    public void setSearchMonthCount(long searchMonthCount) {
        this.searchMonthCount = searchMonthCount;
    }

    public long getUpdateCount() {
        return updateCount;
    }

    public void setUpdateCount(long updateCount) {
        this.updateCount = updateCount;
    }

    /**
     * toString return json format string of this bean
     * @return String
     */
    public String toString() {
        return com.fortune.util.JsonUtils.getJsonString(this);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getSimpleJson() {
        return com.fortune.util.JsonUtils.getJsonString(this, null);
    }

    @SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
    public String getObjJson() {
        return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
    }
}
