package com.fortune.rms.business.module.model;

import com.fortune.common.business.base.model.BaseModel;

/**
 * Module generated by hbm2java
 */
public class Module extends BaseModel {

	private long id;
	private String name;
	private String code;
	private String desp;
	private Long status;
    private Long type;//模式，1电影模式：有点播连接，2新闻模式：图文混排，文字多，3图片模式，图片为主，无点播连接
    private Long columns;//录入信息中，列数，默认是2列
    private Long channelId;
    private boolean selected;

	public Module() {
	}

	public Module(long id) {
		this.id = id;
	}

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }


    public Module(long id, String name, String code, String desp, Long status, Long type, Long columns,Long channelId) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.desp = desp;
        this.status = status;
        this.type = type;
        this.columns = columns;
        this.channelId = channelId;
    }

    public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

    public Long getType() {
        return type;
    }

    public void setType(Long type) {
        this.type = type;
    }

    public Long getColumns() {
        return columns;
    }

    public void setColumns(Long columns) {
        this.columns = columns;
    }

    public Long getChannelId() {
        return channelId;
    }

    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }
}
