package com.fortune.rms.business.module.model;

/**
 * PropertySelect generated by hbm2java
 */
public class PropertySelect implements java.io.Serializable {

	private long id;
    private Long value;
	private String code;
	private String name;
	private Long propertyId;
	private Long displayOrder;
	private Long parentId;
	private Long status;

	public PropertySelect() {
	}

	public PropertySelect(long id) {
		this.id = id;
	}

	public PropertySelect(long id,Long value, String code, String name, Long propertyId,
			Long displayOrder, Long parentId, Long status) {
		this.id = id;
        this.value = value;
		this.code = code;
		this.name = name;
		this.propertyId = propertyId;
		this.displayOrder = displayOrder;
		this.parentId = parentId;
		this.status = status;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

    public Long getValue() {
        return value;
    }

    public void setValue(Long value) {
        this.value = value;
    }

    public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public Long getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(Long propertyId) {
		this.propertyId = propertyId;
	}
	public Long getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Long displayOrder) {
		this.displayOrder = displayOrder;
	}
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
