package com.fortune.rms.business.portal.model;

import java.util.Date;

/**
 * UserReview generated by hbm2java
 */
public class UserReviewKeyword implements java.io.Serializable {

	private long id;
	private Long cspId; 
	private String word;
    private String cspName;

	public UserReviewKeyword() {
	}

	public UserReviewKeyword(long id) {
		this.id = id;
	}
	public UserReviewKeyword(long id, Long cspId, String word) {
		this.id = id;
		this.cspId = cspId;
    	this.word = word;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    /**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

    public String getCspName() {
        return cspName;
    }

    public void setCspName(String cspName) {
        this.cspName = cspName;
    }
}
