package com.fortune.rms.business.portal.model;

import java.util.Date;

/**
 * UserReviewReport generated by hbm2java
 */
public class UserReviewReport implements java.io.Serializable {

	private long id;
	private Long userReviewId;
	private String userIp;
	private String desp;
	private Date time;
    private Long status;

	public UserReviewReport() {
	}

	public UserReviewReport(long id) {
		this.id = id;
	}
	public UserReviewReport(long id, Long userReviewId, String userIp,
			String desp, Date time) {
		this.id = id;
		this.userReviewId = userReviewId;
		this.userIp = userIp;
		this.desp = desp;
		this.time = time;
	}

    public UserReviewReport(long id, Long userReviewId, String userIp, String desp, Date time, Long status) {
        this.id = id;
        this.userReviewId = userReviewId;
        this.userIp = userIp;
        this.desp = desp;
        this.time = time;
        this.status = status;
    }

    public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getUserReviewId() {
		return this.userReviewId;
	}

	public void setUserReviewId(Long userReviewId) {
		this.userReviewId = userReviewId;
	}
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}
	public String getDesp() {
		return this.desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

    public Long getStatus() {
        return status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }
}
