package com.fortune.rms.business.csp.model;

import com.fortune.common.business.security.model.Admin;

/**
 * AdminCsp generated by hbm2java
 */
public class AdminCsp implements java.io.Serializable {

	private Integer id;
	private Integer adminId;
	private Integer cspId;
    private Admin admin;
    private Csp csp;
	private Integer isDefaultCsp;

	public AdminCsp() {
	}

	public AdminCsp(Integer id) {
		this.id = id;
	}
	public AdminCsp(Integer id, Integer adminId, Integer cspId, Integer isDefaultCsp) {
		this.id = id;
		this.adminId = adminId;
		this.cspId = cspId;
		this.isDefaultCsp = isDefaultCsp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}
	public Integer getCspId() {
		return this.cspId;
	}

	public void setCspId(Integer cspId) {
		this.cspId = cspId;
	}
	public Integer getIsDefaultCsp() {
		return this.isDefaultCsp;
	}

	public void setIsDefaultCsp(Integer isDefaultCsp) {
		this.isDefaultCsp = isDefaultCsp;
	}

    public Admin getAdmin() {
        return admin;
    }

    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    public Csp getCsp() {
        return csp;
    }

    public void setCsp(Csp csp) {
        this.csp = csp;
    }

    /**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
