package com.fortune.rms.business.csp.model;

/**
 * CspAuditor generated by hbm2java
 */
public class CspAuditor implements java.io.Serializable {

	private long id;
	private Long cspId;
	private Long adminId;
	private Long cpOnline;
	private Long cpOffline;
	private Long spOnline;
	private Long spOffline;

	public CspAuditor() {
	}

	public CspAuditor(long id) {
		this.id = id;
	}
	public CspAuditor(long id, Long cspId, Long adminId, Long cpOnline,
			Long cpOffline, Long spOnline, Long spOffline) {
		this.id = id;
		this.cspId = cspId;
		this.adminId = adminId;
		this.cpOnline = cpOnline;
		this.cpOffline = cpOffline;
		this.spOnline = spOnline;
		this.spOffline = spOffline;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Long adminId) {
		this.adminId = adminId;
	}
	public Long getCpOnline() {
		return this.cpOnline;
	}

	public void setCpOnline(Long cpOnline) {
		this.cpOnline = cpOnline;
	}
	public Long getCpOffline() {
		return this.cpOffline;
	}

	public void setCpOffline(Long cpOffline) {
		this.cpOffline = cpOffline;
	}
	public Long getSpOnline() {
		return this.spOnline;
	}

	public void setSpOnline(Long spOnline) {
		this.spOnline = spOnline;
	}
	public Long getSpOffline() {
		return this.spOffline;
	}

	public void setSpOffline(Long spOffline) {
		this.spOffline = spOffline;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
