package com.fortune.rms.business.csp.model;

/**
 * CspCsp generated by hbm2java
 */
public class CspCsp implements java.io.Serializable {

	private long id;
	private Long masterCspId;
	private Long cspId;

	public CspCsp() {
	}

	public CspCsp(long id) {
		this.id = id;
	}
	public CspCsp(long id, Long masterCspId, Long cspId) {
		this.id = id;
		this.masterCspId = masterCspId;
		this.cspId = cspId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getMasterCspId() {
		return this.masterCspId;
	}

	public void setMasterCspId(Long masterCspId) {
		this.masterCspId = masterCspId;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
