package com.fortune.rms.business.csp.model;

/**
 * CspDevice generated by hbm2java
 */
public class CspDevice implements java.io.Serializable {

	private long id;
	private Long cspId;
	private Long deviceId;

	public CspDevice() {
	}

	public CspDevice(long id) {
		this.id = id;
	}
	public CspDevice(long id, Long cspId, Long deviceId) {
		this.id = id;
		this.cspId = cspId;
		this.deviceId = deviceId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Long deviceId) {
		this.deviceId = deviceId;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
