package com.fortune.rms.business.csp.model;

/**
 * CspModule generated by hbm2java
 */
public class CspModule implements java.io.Serializable {

	private long id;
	private Long cspId;
	private Long moduleId;
	private Long isDefault;

	public CspModule() {
	}

	public CspModule(long id) {
		this.id = id;
	}

    public CspModule(long id, Long cspId, Long moduleId) {
        this.id = id;
        this.cspId = cspId;
        this.moduleId = moduleId;
    }

    public CspModule(long id, Long cspId, Long moduleId, Long isDefault) {
		this.id = id;
		this.cspId = cspId;
		this.moduleId = moduleId;
		this.isDefault = isDefault;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Long moduleId) {
		this.moduleId = moduleId;
	}
	public Long getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Long isDefault) {
		this.isDefault = isDefault;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
