package com.fortune.rms.business.csp.model;

/**
 * CspProduct generated by hbm2java
 */
public class CspProduct implements java.io.Serializable {

	private long id;
	private Long cspId;
	private Long productId;

	public CspProduct() {
	}

	public CspProduct(long id) {
		this.id = id;
	}
	public CspProduct(long id, Long cspId, Long productId) {
		this.id = id;
		this.cspId = cspId;
		this.productId = productId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
