package com.fortune.rms.business.product.model;

import com.fortune.common.business.base.model.BaseModel;

/**
 * Product generated by hbm2java
 */
public class Product extends BaseModel {

	private long id;
	private String name;
	private String payProductNo;
	private Double price;
	private Long type;
	private Long validLength;
	private Long lengthUnit;
	private Long autoPay;
	private Long searchExtra;
	private Long status;
    private boolean selected;
    private Long mobileProduct;
    private Long costType;
    private String description;
	public Product() {
	}

	public Product(long id) {
		this.id = id;
	}

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public Product(long id, String name, String payProductNo, Double price, Long type, Long validLength,
                   Long lengthUnit, Long autoPay, Long searchExtra, Long status, boolean selected, Long mobileProduct,
                   Long costType,String description) {
        this.id = id;
        this.name = name;
        this.payProductNo = payProductNo;
        this.price = price;
        this.type = type;
        this.validLength = validLength;
        this.lengthUnit = lengthUnit;
        this.autoPay = autoPay;
        this.searchExtra = searchExtra;
        this.status = status;
        this.selected = selected;
        this.mobileProduct = mobileProduct;
        this.costType = costType;
        this.description = description;
    }

//    public Product(long id, String name, String payProductNo, Double price,
//			Long type, Long validLength, Long lengthUnit, Long autoPay,
//			Long searchExtra, Long status) {
//		this.id = id;
//		this.name = name;
//		this.payProductNo = payProductNo;
//		this.price = price;
//		this.type = type;
//		this.validLength = validLength;
//		this.lengthUnit = lengthUnit;
//		this.autoPay = autoPay;
//		this.searchExtra = searchExtra;
//		this.status = status;
//	}


    public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getPayProductNo() {
		return this.payProductNo;
	}

    public Long getMobileProduct() {
        return mobileProduct;
    }

    public void setMobileProduct(Long mobileProduct) {
        this.mobileProduct = mobileProduct;
    }

    public void setPayProductNo(String payProductNo) {
		this.payProductNo = payProductNo;
	}
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}
	public Long getValidLength() {
		return this.validLength;
	}

	public void setValidLength(Long validLength) {
		this.validLength = validLength;
	}
	public Long getLengthUnit() {
		return this.lengthUnit;
	}

	public void setLengthUnit(Long lengthUnit) {
		this.lengthUnit = lengthUnit;
	}
	public Long getAutoPay() {
		return this.autoPay;
	}

	public void setAutoPay(Long autoPay) {
		this.autoPay = autoPay;
	}
	public Long getSearchExtra() {
		return this.searchExtra;
	}

	public void setSearchExtra(Long searchExtra) {
		this.searchExtra = searchExtra;
	}
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

    public Long getCostType() {
        return costType;
    }

    public void setCostType(Long costType) {
        this.costType = costType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
