package com.fortune.rms.business.product.model;

import java.util.Date;

/**
 * ServiceProduct generated by hbm2java
 */
public class ServiceProduct implements java.io.Serializable {
     public static final long PRIORITY_CSPID= 0;

	private long id;
	private String name;
	private Long type;
	private Long cspId;
	private Long productId;
	private Long validLength;
	private Long lengthUnit;
	private Long status;
	private Long autoPay;
	private Long searchExtra;
	private Long discount;
	private Date discountStartTime;
	private Date discountEndTime;
	private Long isFree;
	private Date freeStartTime;
	private Date freeEndTime;
	private Long isDisplayMsg;
	private String msg;
	private Date msgStartTime;
	private Date msgEndTime;
	private Long isDisplayGift;
    private boolean selected;

    private String productName;

	public ServiceProduct() {
	}
    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }
	public ServiceProduct(Long id) {
		this.id = id;
	}
	public ServiceProduct(long id, String name, Long type, Long cspId,
			Long productId, Long validLength, Long lengthUnit, Long status,
			Long autoPay, Long searchExtra, Long discount,
			Date discountStartTime, Date discountEndTime, Long isFree,
			Date freeStartTime, Date freeEndTime, Long isDisplayMsg,
			String msg, Date msgStartTime, Date msgEndTime, Long isDisplayGift) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.cspId = cspId;
		this.productId = productId;
		this.validLength = validLength;
		this.lengthUnit = lengthUnit;
		this.status = status;
		this.autoPay = autoPay;
		this.searchExtra = searchExtra;
		this.discount = discount;
		this.discountStartTime = discountStartTime;
		this.discountEndTime = discountEndTime;
		this.isFree = isFree;
		this.freeStartTime = freeStartTime;
		this.freeEndTime = freeEndTime;
		this.isDisplayMsg = isDisplayMsg;
		this.msg = msg;
		this.msgStartTime = msgStartTime;
		this.msgEndTime = msgEndTime;
		this.isDisplayGift = isDisplayGift;
	}

    public String getProductName() {
         return productName;
     }

     public void setProductName(String productName) {
         this.productName = productName;
     }
    
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public Long getType() {
		return this.type;
	}

	public void setType(Long type) {
		this.type = type;
	}
	public Long getCspId() {
		return this.cspId;
	}

	public void setCspId(Long cspId) {
		this.cspId = cspId;
	}
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}
	public Long getValidLength() {
		return this.validLength;
	}

	public void setValidLength(Long validLength) {
		this.validLength = validLength;
	}
	public Long getLengthUnit() {
		return this.lengthUnit;
	}

	public void setLengthUnit(Long lengthUnit) {
		this.lengthUnit = lengthUnit;
	}
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}
	public Long getAutoPay() {
		return this.autoPay;
	}

	public void setAutoPay(Long autoPay) {
		this.autoPay = autoPay;
	}
	public Long getSearchExtra() {
		return this.searchExtra;
	}

	public void setSearchExtra(Long searchExtra) {
		this.searchExtra = searchExtra;
	}
	public Long getDiscount() {
		return this.discount;
	}

	public void setDiscount(Long discount) {
		this.discount = discount;
	}
	public Date getDiscountStartTime() {
		return this.discountStartTime;
	}

	public void setDiscountStartTime(Date discountStartTime) {
		this.discountStartTime = discountStartTime;
	}
	public Date getDiscountEndTime() {
		return this.discountEndTime;
	}

	public void setDiscountEndTime(Date discountEndTime) {
		this.discountEndTime = discountEndTime;
	}
	public Long getIsFree() {
		return this.isFree;
	}

	public void setIsFree(Long isFree) {
		this.isFree = isFree;
	}
	public Date getFreeStartTime() {
		return this.freeStartTime;
	}

	public void setFreeStartTime(Date freeStartTime) {
		this.freeStartTime = freeStartTime;
	}
	public Date getFreeEndTime() {
		return this.freeEndTime;
	}

	public void setFreeEndTime(Date freeEndTime) {
		this.freeEndTime = freeEndTime;
	}
	public Long getIsDisplayMsg() {
		return this.isDisplayMsg;
	}

	public void setIsDisplayMsg(Long isDisplayMsg) {
		this.isDisplayMsg = isDisplayMsg;
	}
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}
	public Date getMsgStartTime() {
		return this.msgStartTime;
	}

	public void setMsgStartTime(Date msgStartTime) {
		this.msgStartTime = msgStartTime;
	}
	public Date getMsgEndTime() {
		return this.msgEndTime;
	}

	public void setMsgEndTime(Date msgEndTime) {
		this.msgEndTime = msgEndTime;
	}
	public Long getIsDisplayGift() {
		return this.isDisplayGift;
	}

	public void setIsDisplayGift(Long isDisplayGift) {
		this.isDisplayGift = isDisplayGift;
	}

	/**
	 * toString return json format string of this bean
	 * @return String
	 */
	public String toString() {
		return com.fortune.util.JsonUtils.getJsonString(this);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getSimpleJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, null);
	}

	@SuppressWarnings({"JpaAttributeMemberSignatureInspection"})
	public String getObjJson() {
		return com.fortune.util.JsonUtils.getJsonString(this, "obj.");
	}

}
